/**
 *
 * @author Thant Sin
 */
package SmartForestMonitoring;

import com.forest.weather.WeatherRequest;
import com.forest.weather.WeatherResponse;
import com.forest.weather.WeatherStreamRequest;
import com.forest.weather.WeatherServiceGrpc;
import com.forest.firerisk.FireRiskRequest;
import com.forest.firerisk.FireRiskResponse;
import com.forest.firerisk.FireRiskServiceGrpc;
import com.forest.alert.SensorReading;
import com.forest.alert.SensorReport;
import com.forest.alert.AlertEvent;
import com.forest.alert.AlertCommand;
import com.forest.alert.AlertServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Metadata;
import io.grpc.StatusRuntimeException;
import io.grpc.stub.MetadataUtils;
import io.grpc.stub.StreamObserver;
import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.InetAddress;
import java.util.Iterator;
import java.util.Random;

public class ClientGUI extends JFrame {

    // Auth token loaded from environment variable — never hardcoded
    private static final String AUTH_TOKEN = System.getenv("FOREST_MONITOR_TOKEN") != null
            ? System.getenv("FOREST_MONITOR_TOKEN")
            : "";

    // gRPC stubs
    private WeatherServiceGrpc.WeatherServiceBlockingStub weatherStub;
    private WeatherServiceGrpc.WeatherServiceStub weatherAsyncStub;
    private FireRiskServiceGrpc.FireRiskServiceBlockingStub fireRiskStub;
    private AlertServiceGrpc.AlertServiceStub alertStub;

    // Channels stored as fields so they can be shut down cleanly
    private ManagedChannel weatherChannel;
    private ManagedChannel fireRiskChannel;
    private ManagedChannel alertChannel;

    // Random generator for Weather and Alert services (simulating sensors)
    private final Random rand = new Random();

    // Result area
    private JTextArea resultArea;

    // Zone dropdown options
    private static final String[] ZONES = {
        "ZONE_A", "ZONE_B", "ZONE_C", "ZONE_D", "ZONE_E",
        "NORTH_FOREST", "SOUTH_FOREST"
    };

    // Weather components
    private JComboBox<String> weatherZoneCombo;
    private JTextField durationField;

    // Fire Risk components — manual input by user
    private JComboBox<String> fireZoneCombo;
    private JTextField fireTempField;
    private JTextField fireWindField;
    private JTextField fireHumidityField;
    private JTextField fireSmokeField;

    // Alert components — auto-generated
    private JComboBox<String> alertZoneCombo;
    private JTextField alertSmokeField;
    private JTextField alertTempField;
    private StreamObserver<SensorReading> sensorStream;
    private StreamObserver<AlertEvent> alertStream;

    // Lock object to protect sensorStream from race conditions
    private final Object sensorStreamLock = new Object();

    public ClientGUI() {
        setTitle("Smart Forest Monitoring System");
        setSize(950, 720);

        // Handle window close so channels are shut down cleanly
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                shutdownChannels();
                dispose();
                System.exit(0);
            }
        });

        setLayout(new BorderLayout());

        // Title
        JLabel title = new JLabel("Smart Forest Monitoring System", SwingConstants.CENTER);
        title.setFont(new Font("Arial", Font.BOLD, 18));
        title.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        add(title, BorderLayout.NORTH);

        // Main panel
        JPanel mainPanel = new JPanel(new GridLayout(3, 1, 5, 5));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        // ===== WEATHER SERVICE PANEL =====
        // Weather data is auto-generated by server (simulating real sensors)
        JPanel weatherPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        weatherPanel.setBorder(BorderFactory.createTitledBorder(
                "Weather Service (Unary + Server Streaming)"));
        weatherPanel.add(new JLabel("Zone:"));
        weatherZoneCombo = new JComboBox<>(ZONES);
        weatherPanel.add(weatherZoneCombo);
        weatherPanel.add(new JLabel("Stream Count:"));
        durationField = new JTextField("5", 4);
        weatherPanel.add(durationField);
        JButton getWeatherBtn = new JButton("Get Weather (Unary)");
        JButton streamWeatherBtn = new JButton("Stream Weather (Server Stream)");
        getWeatherBtn.addActionListener(e -> getWeather());
        streamWeatherBtn.addActionListener(e -> streamWeather());
        weatherPanel.add(getWeatherBtn);
        weatherPanel.add(streamWeatherBtn);
        mainPanel.add(weatherPanel);

        // ===== FIRE RISK SERVICE PANEL =====
        // User manually inputs sensor readings (simulating a field officer)
        JPanel firePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        firePanel.setBorder(BorderFactory.createTitledBorder(
                "Fire Risk Service (Unary) — Enter sensor readings manually"));
        firePanel.add(new JLabel("Zone:"));
        fireZoneCombo = new JComboBox<>(ZONES);
        firePanel.add(fireZoneCombo);
        firePanel.add(new JLabel("Temp(°C):"));
        fireTempField = new JTextField("38.0", 5);
        firePanel.add(fireTempField);
        firePanel.add(new JLabel("Wind(km/h):"));
        fireWindField = new JTextField("45.0", 5);
        firePanel.add(fireWindField);
        firePanel.add(new JLabel("Humidity(%):"));
        fireHumidityField = new JTextField("20.0", 5);
        firePanel.add(fireHumidityField);
        firePanel.add(new JLabel("Smoke:"));
        fireSmokeField = new JTextField("6.0", 5);
        firePanel.add(fireSmokeField);
        JButton assessBtn = new JButton("Assess Risk (Unary)");
        assessBtn.addActionListener(e -> assessFireRisk());
        firePanel.add(assessBtn);
        mainPanel.add(firePanel);

        // ===== ALERT SERVICE PANEL =====
        // Alert data is auto-generated (simulating real sensors)
        JPanel alertPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        alertPanel.setBorder(BorderFactory.createTitledBorder(
                "Alert Service (Client Streaming + BiDi) — Auto-generated sensor data"));
        alertPanel.add(new JLabel("Zone:"));
        alertZoneCombo = new JComboBox<>(ZONES);
        alertPanel.add(alertZoneCombo);
        alertPanel.add(new JLabel("Smoke:"));
        alertSmokeField = new JTextField("--", 5);
        alertSmokeField.setEditable(false);
        alertSmokeField.setBackground(new Color(230, 230, 230));
        alertPanel.add(alertSmokeField);
        alertPanel.add(new JLabel("Temp:"));
        alertTempField = new JTextField("--", 5);
        alertTempField.setEditable(false);
        alertTempField.setBackground(new Color(230, 230, 230));
        alertPanel.add(alertTempField);
        JButton prepareUploadBtn = new JButton("Prepare Upload (Client Stream)");
        JButton sendReadingBtn   = new JButton("Send Reading");
        JButton finishUploadBtn  = new JButton("Finish Upload");
        JButton monitorBtn       = new JButton("Monitor Alerts (BiDi)");
        prepareUploadBtn.addActionListener(e -> prepareUpload());
        sendReadingBtn.addActionListener(e -> sendReading());
        finishUploadBtn.addActionListener(e -> finishUpload());
        monitorBtn.addActionListener(e -> monitorAlerts());
        alertPanel.add(prepareUploadBtn);
        alertPanel.add(sendReadingBtn);
        alertPanel.add(finishUploadBtn);
        alertPanel.add(monitorBtn);
        mainPanel.add(alertPanel);

        add(mainPanel, BorderLayout.CENTER);

        // Result area
        resultArea = new JTextArea(15, 60);
        resultArea.setEditable(false);
        resultArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollPane = new JScrollPane(resultArea);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Result"));
        add(scrollPane, BorderLayout.SOUTH);

        // Connect to services on startup
        connectToServices();
    }

    // ========== BUILD AUTH METADATA HEADER ==========
    private Metadata buildAuthHeader() {
        Metadata headers = new Metadata();
        headers.put(Metadata.Key.of("auth-token", Metadata.ASCII_STRING_MARSHALLER), AUTH_TOKEN);
        return headers;
    }

    // ========== CONNECT TO SERVICES VIA NAMING SERVICE ==========
    private void connectToServices() {
        shutdownChannels();
        try {
            JmDNS jmdns = JmDNS.create(InetAddress.getLocalHost());

            ServiceInfo weatherInfo = jmdns.getServiceInfo(NamingServer.SERVICE_TYPE, "WeatherService");
            ServiceInfo fireInfo    = jmdns.getServiceInfo(NamingServer.SERVICE_TYPE, "FireRiskService");
            ServiceInfo alertInfo   = jmdns.getServiceInfo(NamingServer.SERVICE_TYPE, "AlertService");

            // Weather Service
            if (weatherInfo != null) {
                weatherChannel = ManagedChannelBuilder
                        .forAddress(weatherInfo.getHostAddresses()[0], weatherInfo.getPort())
                        .usePlaintext().build();
                appendResult("Connected to WeatherService on port " + weatherInfo.getPort());
            } else {
                appendResult("WeatherService not found. Using default port 50051.");
                weatherChannel = ManagedChannelBuilder
                        .forAddress("localhost", 50051).usePlaintext().build();
            }
            weatherStub = WeatherServiceGrpc.newBlockingStub(weatherChannel)
                    .withInterceptors(MetadataUtils.newAttachHeadersInterceptor(buildAuthHeader()));
            weatherAsyncStub = WeatherServiceGrpc.newStub(weatherChannel)
                    .withInterceptors(MetadataUtils.newAttachHeadersInterceptor(buildAuthHeader()));

            // Fire Risk Service
            if (fireInfo != null) {
                fireRiskChannel = ManagedChannelBuilder
                        .forAddress(fireInfo.getHostAddresses()[0], fireInfo.getPort())
                        .usePlaintext().build();
                appendResult("Connected to FireRiskService on port " + fireInfo.getPort());
            } else {
                appendResult("FireRiskService not found. Using default port 50052.");
                fireRiskChannel = ManagedChannelBuilder
                        .forAddress("localhost", 50052).usePlaintext().build();
            }
            fireRiskStub = FireRiskServiceGrpc.newBlockingStub(fireRiskChannel)
                    .withInterceptors(MetadataUtils.newAttachHeadersInterceptor(buildAuthHeader()));

            // Alert Service
            if (alertInfo != null) {
                alertChannel = ManagedChannelBuilder
                        .forAddress(alertInfo.getHostAddresses()[0], alertInfo.getPort())
                        .usePlaintext().build();
                appendResult("Connected to AlertService on port " + alertInfo.getPort());
            } else {
                appendResult("AlertService not found. Using default port 50053.");
                alertChannel = ManagedChannelBuilder
                        .forAddress("localhost", 50053).usePlaintext().build();
            }
            alertStub = AlertServiceGrpc.newStub(alertChannel)
                    .withInterceptors(MetadataUtils.newAttachHeadersInterceptor(buildAuthHeader()));

        } catch (IOException e) {
            appendResult("Error connecting to services: " + e.getMessage());
        }
    }

    // ========== SHUTDOWN CHANNELS CLEANLY ==========
    private void shutdownChannels() {
        if (weatherChannel  != null && !weatherChannel.isShutdown())  weatherChannel.shutdown();
        if (fireRiskChannel != null && !fireRiskChannel.isShutdown()) fireRiskChannel.shutdown();
        if (alertChannel    != null && !alertChannel.isShutdown())    alertChannel.shutdown();
    }

    // ========== GRPC ERROR HANDLER ==========
    // Handles specific gRPC status codes with meaningful messages
    private void handleGrpcError(String operation, StatusRuntimeException e) {
        switch (e.getStatus().getCode()) {
            case UNAUTHENTICATED:
                appendResult("[" + operation + "] Authentication failed: "
                        + e.getStatus().getDescription());
                break;
            case INVALID_ARGUMENT:
                appendResult("[" + operation + "] Invalid input: "
                        + e.getStatus().getDescription());
                break;
            case UNAVAILABLE:
                appendResult("[" + operation + "] Service unavailable. Is the server running?");
                break;
            case CANCELLED:
                appendResult("[" + operation + "] Request was cancelled.");
                break;
            case DEADLINE_EXCEEDED:
                appendResult("[" + operation + "] Request timed out.");
                break;
            default:
                appendResult("[" + operation + "] Error "
                        + e.getStatus().getCode() + ": "
                        + e.getStatus().getDescription());
        }
    }

    // ========== WEATHER - UNARY RPC ==========
    private void getWeather() {
        try {
            String zone = (String) weatherZoneCombo.getSelectedItem();
            WeatherRequest request = WeatherRequest.newBuilder()
                    .setZoneId(zone).build();
            WeatherResponse response = weatherStub.getWeatherStatus(request);
            appendResult("\n--- Weather Status [" + response.getZoneId() + "] ---");
            appendResult("Temperature : " + String.format("%.1f", response.getTemperature()) + " °C");
            appendResult("Wind Speed  : " + String.format("%.1f", response.getWindSpeed()) + " km/h");
            appendResult("Humidity    : " + String.format("%.1f", response.getHumidity()) + " %");
            appendResult("Rainfall    : " + String.format("%.1f", response.getRainfall()) + " mm");
            appendResult("Status      : " + response.getStatus());
            appendResult("Timestamp   : " + response.getTimestamp());
        } catch (StatusRuntimeException e) {
            handleGrpcError("Get Weather", e);
        } catch (Exception e) {
            appendResult("Get Weather Error: " + e.getMessage());
        }
    }

    // ========== WEATHER - SERVER STREAMING RPC ==========
    private void streamWeather() {
        new Thread(() -> {
            try {
                String zone = (String) weatherZoneCombo.getSelectedItem();
                int duration = Integer.parseInt(durationField.getText());
                WeatherStreamRequest request = WeatherStreamRequest.newBuilder()
                        .setZoneId(zone)
                        .setDuration(duration)
                        .build();
                appendResult("\n--- Streaming Weather Updates for " + zone + " ---");
                Iterator<WeatherResponse> responses = weatherStub.streamWeatherUpdates(request);
                while (responses.hasNext()) {
                    WeatherResponse r = responses.next();
                    appendResult("[" + r.getTimestamp() + "] Temp: "
                            + String.format("%.1f", r.getTemperature()) + "°C"
                            + "  Wind: " + String.format("%.1f", r.getWindSpeed()) + "km/h"
                            + "  Status: " + r.getStatus());
                }
                appendResult("--- Stream Complete ---");
            } catch (StatusRuntimeException e) {
                handleGrpcError("Stream Weather", e);
            } catch (NumberFormatException e) {
                appendResult("Invalid stream count. Please enter a valid number.");
            } catch (Exception e) {
                appendResult("Stream Weather Error: " + e.getMessage());
            }
        }).start();
    }

    // ========== FIRE RISK - UNARY RPC ==========
    // User manually inputs sensor readings — simulating a field officer
    private void assessFireRisk() {
        try {
            String zone = (String) fireZoneCombo.getSelectedItem();

            // Read values entered manually by the user
            float temp     = Float.parseFloat(fireTempField.getText());
            float wind     = Float.parseFloat(fireWindField.getText());
            float humidity = Float.parseFloat(fireHumidityField.getText());
            float smoke    = Float.parseFloat(fireSmokeField.getText());

            // Input validation
            if (temp < 0 || temp > 60) {
                appendResult("Temperature must be between 0 and 60°C"); return;
            }
            if (wind < 0 || wind > 150) {
                appendResult("Wind speed must be between 0 and 150 km/h"); return;
            }
            if (humidity < 0 || humidity > 100) {
                appendResult("Humidity must be between 0 and 100%"); return;
            }
            if (smoke < 0 || smoke > 10) {
                appendResult(" Smoke level must be between 0 and 10"); return;
            }

            FireRiskRequest request = FireRiskRequest.newBuilder()
                    .setZoneId(zone)
                    .setTemperature(temp)
                    .setWindSpeed(wind)
                    .setHumidity(humidity)
                    .setSmokeLevel(smoke)
                    .build();

            FireRiskResponse response = fireRiskStub.assessFireRisk(request);
            appendResult("\n--- Fire Risk Assessment [" + response.getZoneId() + "] ---");
            appendResult("Input Data      : Temp=" + String.format("%.1f", temp)
                    + "°C  Wind=" + String.format("%.1f", wind)
                    + "km/h  Humidity=" + String.format("%.1f", humidity)
                    + "%  Smoke=" + String.format("%.1f", smoke));
            appendResult("Risk Level      : " + response.getRiskLevel());
            appendResult("Risk Score      : " + String.format("%.1f", response.getRiskScore()) + "/100");
            appendResult("Recommendation  : " + response.getRecommendation());
            appendResult("Timestamp       : " + response.getTimestamp());

        } catch (StatusRuntimeException e) {
            handleGrpcError("Assess Fire Risk", e);
        } catch (NumberFormatException e) {
            appendResult("Invalid input. Please enter valid numbers in all fields.");
        } catch (Exception e) {
            appendResult("Assess Fire Risk Error: " + e.getMessage());
        }
    }

    // ========== ALERT - CLIENT STREAMING RPC ==========
    private void prepareUpload() {
        String zone = (String) alertZoneCombo.getSelectedItem();
        synchronized (sensorStreamLock) {
            sensorStream = alertStub.uploadSensorReadings(new StreamObserver<SensorReport>() {
                @Override
                public void onNext(SensorReport report) {
                    appendResult("\n--- Sensor Upload Report [" + zone + "] ---");
                    appendResult("Avg Smoke    : " + String.format("%.2f", report.getAverageSmokeLevel()));
                    appendResult("Max Smoke    : " + String.format("%.2f", report.getMaxSmokeLevel()));
                    appendResult("Avg Temp     : " + String.format("%.2f", report.getAverageTemperature()) + " °C");
                    appendResult("Max Temp     : " + String.format("%.2f", report.getMaxTemperature()) + " °C");
                    appendResult("Alert Flag   : " + report.getAlertFlag());
                    appendResult("Summary      : " + report.getSummary());
                }
                @Override
                public void onError(Throwable t) {
                    if (t instanceof StatusRuntimeException) {
                        handleGrpcError("Upload Sensor Readings", (StatusRuntimeException) t);
                    } else {
                        appendResult("Upload error: " + t.getMessage());
                    }
                }
                @Override
                public void onCompleted() {
                    appendResult("--- Upload Stream Closed ---");
                }
            });
        }
        appendResult("\n Upload stream prepared for " + zone
                + ". Click 'Send Reading' to upload sensor data.");
    }

    private void sendReading() {
        synchronized (sensorStreamLock) {
            if (sensorStream == null) {
                appendResult("Please click 'Prepare Upload' first!");
                return;
            }
            String zone = (String) alertZoneCombo.getSelectedItem();

            // Auto-generate random sensor readings (simulating real sensors)
            float smoke = rand.nextFloat() * 10;
            float temp  = 20 + rand.nextFloat() * 30;

            alertSmokeField.setText(String.format("%.1f", smoke));
            alertTempField.setText(String.format("%.1f", temp));

            SensorReading reading = SensorReading.newBuilder()
                    .setZoneId(zone)
                    .setSmokeReading(smoke)
                    .setTemperatureReading(temp)
                    .build();
            sensorStream.onNext(reading);
            appendResult("Sent reading [" + zone + "]"
                    + " - Smoke: " + String.format("%.1f", smoke)
                    + "  Temp: " + String.format("%.1f", temp) + "°C");
        }
    }

    private void finishUpload() {
        synchronized (sensorStreamLock) {
            if (sensorStream == null) {
                appendResult("o active upload stream!");
                return;
            }
            sensorStream.onCompleted();
            sensorStream = null;
        }
        appendResult("Upload completed. Waiting for server report...");
    }

    // ========== ALERT - BIDIRECTIONAL STREAMING RPC ==========
    private void monitorAlerts() {
        String zone = (String) alertZoneCombo.getSelectedItem();

        // Auto-generate random severity (simulating real sensor alert)
        float severity = rand.nextFloat() * 10;
        alertSmokeField.setText(String.format("%.1f", severity));

        alertStream = alertStub.monitorAlerts(new StreamObserver<AlertCommand>() {
            @Override
            public void onNext(AlertCommand cmd) {
                appendResult("\n COMMAND [" + cmd.getZoneId() + "]: " + cmd.getCommand());
                appendResult("   Message: " + cmd.getMessage());
                appendResult("   Time   : " + cmd.getTimestamp());
            }
            @Override
            public void onError(Throwable t) {
                if (t instanceof StatusRuntimeException) {
                    handleGrpcError("Monitor Alerts", (StatusRuntimeException) t);
                } else {
                    appendResult("Alert stream error: " + t.getMessage());
                }
            }
            @Override
            public void onCompleted() {
                appendResult("--- Alert Stream Closed ---");
            }
        });

        AlertEvent event = AlertEvent.newBuilder()
                .setZoneId(zone)
                .setEventType("SMOKE_DETECTED")
                .setSeverity(severity)
                .build();
        alertStream.onNext(event);
        appendResult("\nBiDi stream started [" + zone + "] - Severity: "
                + String.format("%.1f", severity));
    }

    // ========== HELPER ==========
    private void appendResult(String text) {
        SwingUtilities.invokeLater(() -> resultArea.append(text + "\n"));
    }

    // ========== MAIN ==========
    public static void main(String[] args) {
        // Fail fast if auth token environment variable is not set
        if (AUTH_TOKEN.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "FOREST_MONITOR_TOKEN environment variable is not set.\n"
                    + "Please set it before starting the application.\n"
                    + "Example: set FOREST_MONITOR_TOKEN=forest-monitor-2026",
                    "Configuration Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        SwingUtilities.invokeLater(() -> new ClientGUI().setVisible(true));
    }
}